// <auto-generated />
using System;
using Dofus210.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dofus210.Data.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20260323114133_AddCharactersAndBreeds")]
    partial class AddCharactersAndBreeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dofus210.Data.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsGameMaster")
                        .HasColumnType("bit");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("Dofus210.Data.Entities.Breed", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<int>("FemaleBonesId")
                        .HasColumnType("int");

                    b.Property<string>("FemaleLook")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsPlayable")
                        .HasColumnType("bit");

                    b.Property<int>("MaleBonesId")
                        .HasColumnType("int");

                    b.Property<string>("MaleLook")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Breeds", (string)null);
                });

            modelBuilder.Entity("Dofus210.Data.Entities.Character", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("BonesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<byte>("BreedId")
                        .HasColumnType("tinyint");

                    b.Property<int>("Color1")
                        .HasColumnType("int");

                    b.Property<int>("Color2")
                        .HasColumnType("int");

                    b.Property<int>("Color3")
                        .HasColumnType("int");

                    b.Property<int>("Color4")
                        .HasColumnType("int");

                    b.Property<int>("Color5")
                        .HasColumnType("int");

                    b.Property<short>("CosmeticId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("Experience")
                        .HasColumnType("bigint");

                    b.Property<short>("GameServerId")
                        .HasColumnType("smallint");

                    b.Property<short>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("Sex")
                        .HasColumnType("bit");

                    b.Property<int>("SkinId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("BreedId");

                    b.HasIndex("GameServerId", "Name")
                        .IsUnique();

                    b.ToTable("Characters", (string)null);
                });

            modelBuilder.Entity("Dofus210.Data.Entities.CharacterPosition", b =>
                {
                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint");

                    b.Property<short>("CellId")
                        .HasColumnType("smallint");

                    b.Property<byte>("Direction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)2);

                    b.Property<int>("MapId")
                        .HasColumnType("int");

                    b.HasKey("CharacterId");

                    b.ToTable("CharacterPositions", (string)null);
                });

            modelBuilder.Entity("Dofus210.Data.Entities.CharacterStats", b =>
                {
                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint");

                    b.Property<short>("ActionPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)6);

                    b.Property<short>("EnergyPoints")
                        .HasColumnType("smallint");

                    b.Property<long>("Kamas")
                        .HasColumnType("bigint");

                    b.Property<int>("LifePoints")
                        .HasColumnType("int");

                    b.Property<short>("MaxEnergyPoints")
                        .HasColumnType("smallint");

                    b.Property<int>("MaxLifePoints")
                        .HasColumnType("int");

                    b.Property<short>("MovementPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)3);

                    b.Property<short>("SpellsPoints")
                        .HasColumnType("smallint");

                    b.Property<short>("StatsPoints")
                        .HasColumnType("smallint");

                    b.HasKey("CharacterId");

                    b.ToTable("CharacterStats", (string)null);
                });

            modelBuilder.Entity("Dofus210.Data.Entities.GameServer", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("CanCreateNewCharacter")
                        .HasColumnType("bit");

                    b.Property<byte>("CharacterCapacity")
                        .HasColumnType("tinyint");

                    b.Property<byte>("CommunityId")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Completion")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("GameServers", (string)null);
                });

            modelBuilder.Entity("Dofus210.Data.Entities.Character", b =>
                {
                    b.HasOne("Dofus210.Data.Entities.Account", "Account")
                        .WithMany("Characters")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dofus210.Data.Entities.Breed", "Breed")
                        .WithMany("Characters")
                        .HasForeignKey("BreedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dofus210.Data.Entities.GameServer", "GameServer")
                        .WithMany("Characters")
                        .HasForeignKey("GameServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Breed");

                    b.Navigation("GameServer");
                });

            modelBuilder.Entity("Dofus210.Data.Entities.CharacterPosition", b =>
                {
                    b.HasOne("Dofus210.Data.Entities.Character", "Character")
                        .WithOne("Position")
                        .HasForeignKey("Dofus210.Data.Entities.CharacterPosition", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Dofus210.Data.Entities.CharacterStats", b =>
                {
                    b.HasOne("Dofus210.Data.Entities.Character", "Character")
                        .WithOne("Stats")
                        .HasForeignKey("Dofus210.Data.Entities.CharacterStats", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Dofus210.Data.Entities.Account", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("Dofus210.Data.Entities.Breed", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("Dofus210.Data.Entities.Character", b =>
                {
                    b.Navigation("Position")
                        .IsRequired();

                    b.Navigation("Stats")
                        .IsRequired();
                });

            modelBuilder.Entity("Dofus210.Data.Entities.GameServer", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
