namespace Dofus210.Host.Auth;

public static class DofusMessageIds
{
    public const ushort ProtocolRequired = 1;
    public const ushort HelloConnect = 2607;
    public const ushort Identification = 4;
    public const ushort LoginQueueStatus = 10;
    public const ushort IdentificationFailed = 20;
    public const ushort IdentificationSuccess = 22;
    public const ushort ServersList = 30;
    public const ushort ServerSelection = 40;
    public const ushort SelectedServerRefused = 41;
    public const ushort SelectedServerData = 42;
    public const ushort ServerStatusUpdate = 50;
    public const ushort HelloGame = 101;
    public const ushort AuthenticationTicket = 110;
    public const ushort AuthenticationTicketAccepted = 111;
    public const ushort AuthenticationTicketRefused = 112;
    public const ushort CharactersListRequest = 150;
    public const ushort CharactersList = 151;
    public const ushort CharacterSelection = 152;
    public const ushort CharacterSelectedSuccess = 153;
    public const ushort CharacterCreationRequest = 160;
    public const ushort CharacterCreationResult = 161;
    public const ushort BasicTime = 175;
    public const ushort BasicNoOperation = 176;
    public const ushort BasicPing = 182;
    public const ushort BasicPong = 183;
    public const ushort GameContextCreate = 200;
    public const ushort CurrentMap = 220;
    public const ushort EmoteList = 2285;
    public const ushort MapFightCount = 210;
    public const ushort MapInformationsRequest = 225;
    public const ushort MapComplementaryInformationsData = 226;
    public const ushort CharacterStatsList = 500;
    public const ushort ShortcutBarContent = 3051;
    public const ushort SetCharacterRestrictions = 3701;
    public const ushort InventoryWeight = 5132;
    public const ushort InventoryContent = 5728;
    public const ushort SpellList = 1643;
    public const ushort LifePointsRegenEnd = 9290;
    public const ushort GameContextReadyModern = 5960;
    public const ushort GameContextReadyLegacyCandidate = 6307;
    public const ushort GameMapMovementRequestModern = 3376;
    public const ushort GameMapMovementRequestLegacyCandidate = 4617;
    public const ushort GameCautiousMapMovementRequestModern = 5883;
    public const ushort CharacterLoadingCompleteModern = 7087;
    public const ushort CharacterLoadingCompleteLegacyCandidate = 1599;
    public const ushort ClientKey = 5607;
    public const ushort CredentialsAcknowledgement = 6314;
}
